esphome:
  name: hacan-commissioning-peer

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: ../components

logger:
  level: DEBUG

canbus:
  - platform: esp32_can
    id: hacan_bus
    can_id: 0x000
    bit_rate: 125kbps
    tx_pin: GPIO5
    rx_pin: GPIO4

hacan:
  id: hacan_node
  canbus_id: hacan_bus
  commissioning_role: none

binary_sensor:
  - platform: gpio
    id: in01
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
  - platform: hacan
    id: hacan_in01
    hacan_id: hacan_node
    source_id: in01
    entity_id: 0x01010001
    endpoint: 0x01
    internal: true
